### ISSUE TITLE
Experimenter links with branch references are not scrolled to the branch section when loaded

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#5929] opened 2021-07-12 09:25 UTC
**[Prerequisites]:**
- Have an Desktop experiment in the `Live` or `Completed` state. (eg [here](https://experimenter.services.mozilla.com/nimbus/custom-messaging-in-aboutwelcome-for-chrome-users-to-import))

**[Steps to reproduce]:**
1. Navigate to the Nimbus experiment page from prerequisites and scroll down to the branches section.
2. Click the "#" symbol in front of a branch name and copy the link from the address bar.
3. Open a New Window and navigate to the copied link.
4. Observe the page.

**[Expected result]:**
- The experimenter page is loaded and scrolled to the branch reference.

**[Actual result]:**
- The experimenter page is loaded, but the page is not scrolled to any position.

**[Notes]:**
- The reference works correctly only if the page was already loaded.
- Attached is a screen recording of the issue.

![branch reference links to not scroll the page on first load](https://user-images.githubusercontent.com/18304511/125263986-241e2480-e30c-11eb-804d-f53507b13477.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1480)

**Comment by LZoog** [comment] 2021-07-12 16:09
This is basically a dupe of #5645 since it's the same problem, but I think I'll leave it open separately since it covers a different page.

**Closed** 2021-08-20 21:00 UTC
Labels: WontFix, [QA]:Normal issue, quick-win
