### ISSUE TITLE
You are wrongly redirected to the "URL Not Found" page if you cancel editing after trying to save the name of the experiment only with special characters

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#923] opened 2019-02-13 13:36 UTC
**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.96

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Overview" section.
3. Change the name of the experiment from the "Name" section only with special characters.
4. Click the "Save draft" button.
5. Click the "Cancel Editing" button and observe the behavior. 

**[Expected result]:**
- You are redirected to the main page of the experiment and the changes are not saved.

**[Actual result]:**
- The "The requested URL was not found on this server" page is displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
![urlnotfound](https://user-images.githubusercontent.com/40061643/52715319-d539fc80-2fa4-11e9-9db5-dea57a5838d6.gif)

**Comment by jaredkerim** [comment] 2019-02-27 15:50
@Softvision-RemusDranca Good catch!

**Comment by jaredkerim** [comment] 2019-04-02 19:35
This is a duplicate of https://github.com/mozilla/experimenter/issues/1129

**Closed by jaredkerim** 2019-04-02 19:35 UTC
Labels: [QA]:Normal issue

**Comment by Softvision-RemusDranca** [comment] 2019-05-13 06:34
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.0 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
