### ISSUE TITLE
Missing required 'application' doesn't highlight red after save

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4352] opened 2021-01-05 19:54 UTC
I just noticed if you don't fill in 'application' and click 'save', it highlights the field but doesn't mark it red as required.  It does highlight red if you click a second time anywhere on the page to blur the input, then it highlights red:

Click save:

<img width="1223" alt="Screen Shot 2021-01-05 at 2 52 28 PM" src="https://user-images.githubusercontent.com/119884/103692482-d17f3c80-4f65-11eb-860e-e54bdadbd8bb.png">

Click away:

<img width="1232" alt="Screen Shot 2021-01-05 at 2 54 06 PM" src="https://user-images.githubusercontent.com/119884/103692529-e1971c00-4f65-11eb-8eb6-dd5af8ca9490.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-795)
┆Issue Number: EXP-795

**Comment by data-sync-user** [comment] 2021-05-18 21:37
➤ Jared Kerim commented:

Closing as a duplicate of https://jira.mozilla.com/browse/EXP-632

**Closed by data-sync-user** 2021-05-18 21:37 UTC
Labels: quick-win
