### ISSUE TITLE
Add number formatting to Visualizations

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6263] opened 2021-08-19 21:37 UTC
Via https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment-release/results#mozilla_default_browser

![Default_Browser_Adoption_Experiment_-_Release_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/130145045-c6c084f4-1614-4d39-a4cf-927b16e1a84b.png)

Noted we occasionally have slightly very huge numbers for comparisons which might be nice to add some number formatting to.

ie: "92213.8% - 353037.5%" vs "92,213.8% - "353,037.5%".

Not sure if we can detect if a number is over a certain threshold that we drop the decimal places or not (I could argue that .5 isn't entirely relevant when we're taking 92-353k, but I'm also not a statistics person so I don't know what "close enough" means).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1661)

**Comment by jaredlockhart** [comment] 2021-08-19 21:39
Closing as dupe of https://github.com/mozilla/experimenter/issues/5769

**Closed by jaredlockhart** 2021-08-19 21:39 UTC
