### ISSUE TITLE
Rejected rapid experiment shows as Accepted and has odd button navigation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3151] opened 2020-07-29 16:50 UTC
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/please-reject-me

@k88hudson said on [Slack](https://mozilla.slack.com/archives/C011MC5EB0V/p1596039548192900) that she rejected this experiment, but the UI still shows the experiment as Accepted, and also shows the semi-disabled "Back" and "Request Approval" buttons.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88828986-d7841c80-d180-11ea-9b38-a6b08b1272dc.png)

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88829024-e8cd2900-d180-11ea-9783-47752927a207.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-210)
┆Issue Number: EXP-210

**Comment by pdehaan** [comment] 2020-07-29 16:54
Possibly related: #3003

**Comment by jaredlockhart** [comment] 2020-07-29 17:00
@pdehaan Yep this is basically a duplicate of #3003 since the rejected workflow isn't implemented yet

**Closed** 2020-09-30 19:04 UTC
