### ISSUE TITLE
Highlight fields when saving on Branches page

### ISSUE THREAD

**Issue by eliserichards** [mozilla/experimenter#8345] opened 2023-02-23 17:50 UTC
The overview and audience pages highlight all the fields in the green border and checkmark **after saving** to show that they were validated and saved, but the branches page does not. We should fix that so that we show the valid fields as **green** when saving, it's just a nice UI signal that your stuff was saved properly.

Broken out from https://github.com/mozilla/experimenter/issues/6584

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3188)

**Comment by anand-pb** [comment] 2023-03-08 06:42
I think I will be able to do this @yashikakhurana

**Comment by yashikakhurana** [comment] 2023-03-09 17:52
@anand-pb if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by KramStyles** [comment] 2023-03-11 10:19
@yashikakhurana Can I please be assigned to this task? I'm currently free

**Comment by Sprof22** [comment] 2023-03-12 23:20
@yashikakhurana I am an Outreachy applicant, can I be assigned to this issue

**Comment by yashikakhurana** [comment] 2023-03-13 18:08
@KramStyles @Sprof22 to both of you I have already assigned other issue, feel free to tag again, once you finish that

**Comment by emmaz12** [comment] 2023-03-13 21:43
@yashikakhurana I am interested in taking on this issue! Thanks again :)

**Comment by emmaz12** [comment] 2023-03-20 00:46
@yashikakhurana I am attempting to solve this issue, however, I am struggling to identify where the issue is within the codebase. I am attempting to use PageEditAudience as a reference for how the PageEditBranches component should work, however, I am struggling to identify where the green highlighting is taking place when "Save" is clicked. Would you please provide some guidance? Thanks so much!

**Comment by yashikakhurana** [comment] 2023-03-20 04:22
@emmaz12 more info you can find it here- https://github.com/mozilla/experimenter/pull/8455#issuecomment-1472406310, same issue but you have to fix on branches page, rather than metrics page, I hope this helps, thanks

**Closed** 2023-03-29 15:37 UTC
Labels: good-first-bug, Outreachy
