### ISSUE TITLE
Support feature configs in variants

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3290] opened 2020-08-26 17:29 UTC
This need further discussion, but we need to express a relationship between a `Variant` and a `Feature` (that is, to be able to include feature configs in variants)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-62)
┆Issue Number: EXP-62

**Comment by data-sync-user** [comment] 2020-09-30 18:47
➤ Wil Clouser commented:

Duplicate of EXP-266

**Closed by data-sync-user** 2020-09-30 18:47 UTC
