### ISSUE TITLE
There are noticeable performance issues when navigating Nimbus Results pages

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6268] opened 2021-08-20 16:15 UTC
**[Prerequisites]:**
- Have a complete Nimbus experiment open: 
e.g. https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-ask-and-show-to-pin/results#results_summary
or
https://experimenter.services.mozilla.com/nimbus/1-click-pin-during-onboarding/results#active_hours

**[Steps to reproduce]:**
1. Click “Results Summary” from the navigation menu.
2. Click the “Show Weekly Data” button.
3. Observe the page.

**[Expected result]:**
- The page shows no noticeable performance issues.

**[Actual result]:**
- The page slows down considerably, freezing for a while.

**[Notes]:**
- Clicking any options from the Results navigation menu seems to reproduce the issue.
- I was able to reproduce this on multiple devices using Firefox Nightly 93.0a1 (Build ID: 20210820095755).
- Attached is a recording of the issue.

![freezing](https://user-images.githubusercontent.com/53752296/130262798-86998215-6552-4fb4-9b01-cf6a73637e61.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1663)

**Comment by jaredlockhart** [comment] 2021-08-20 16:20
Looks like we're getting stuck right here:

<img width="2549" alt="Screen Shot 2021-08-20 at 12 18 37 PM" src="https://user-images.githubusercontent.com/119884/130263488-f4e5531a-2c34-4c18-9b3e-0d65e9ec8569.png">

The trace doesn't help us for the prod build, but let me see if I can recreate this in a dev build...

**Comment by jaredlockhart** [comment] 2021-08-20 16:37
Here's that prod experiment dumped to a json file that can be loaded locally with

```
make refresh SKIP_DUMMY=1&&make bash
./manage.py loaddata slow_experiment.json
```


[slow_experiment.json.zip](https://github.com/mozilla/experimenter/files/7022959/slow_experiment.json.zip)

**Comment by jaredlockhart** [comment] 2021-08-20 16:47
This isn't necessarily a 'good first bug' but performance debugging is always fun so if a contributor wants to try digging into this it would probably be a fun puzzle.

**Comment by LZoog** [comment] 2021-08-20 17:39
We discussed this briefly and a solution for this may very well be removing scrollspy, which we have a ticket for (#6249), as it would be very weird if an in-page anchor link was causing rerenders since the DOM is already loaded and there's no prop/state change. There's a comment at the bottom of that file for getting started if someone wants to take a stab at it before we get to it.

**Comment by pdehaan** [comment] 2021-08-20 18:42
I can reproduce this on prod as well, with clicking on nav items in the sidebar (8-12s delay). Same w/ toggling the **"Show Weekly Data"** or any of the **"Show _ Metics"** sections.

Interestingly even HIDING the previously visible section has a noticeable delay; which was unexpected since I assumed it'd just do some CSS `display:none` toggling, but it looks like it might do a full DOM teardown/rebuild each time. In fact, it does seem to toggle between `div class="collapse"` and `div class="collapse show"` as well, so I don't know what is happening behind the scenes&hellip; 🤷 

![Multi-Stage_Onboarding_Ask_And_Show_To_Pin_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/130278018-819e1352-f4d2-4938-88fd-c299b7580179.png)

**Comment by pdehaan** [comment] 2021-08-20 19:03
In fact, here's the /results page results from Google Lighthouse audit in Google Chrome DevTools:

![Multi-Stage_Onboarding_Ask_And_Show_To_Pin_–_Analysis___Experimenter](https://user-images.githubusercontent.com/557895/130281127-7641a2a5-8b99-445c-90a2-ed0a4cce6084.png)

Some performance recommendations:
1. Avoid an excessive DOM size 2,859 elements
2. Minimize main-thread work 5.8s
    Consider reducing the time spent parsing, compiling and executing JS. You may find delivering smaller JS payloads helps with this.

    Category | Time Spent
    -- | --
    Script Evaluation | 4,848 ms
3. Reduce JavaScript execution time 4.9s
    Consider reducing the time spent parsing, compiling, and executing JS. You may find delivering smaller JS payloads helps with this.

    URL | Total CPU Time | Script Evaluation | Script Parse
    -- | -- | -- | --
    …js/main.js(experimenter.services.mozilla.com) | 5,141 ms | 4,664 ms | 26 ms

I'll try poking around the other pages as well and see if I can isolate it to general issues vs page specific issues.

**Comment by jaredlockhart** [comment] 2021-08-20 19:13
Here's the react profiler output:

<img width="1424" alt="Screen Shot 2021-08-20 at 3 12 05 PM" src="https://user-images.githubusercontent.com/119884/130282657-8fd8e5c8-de88-48d4-bd06-f84d62ccb7f9.png">

**Comment by jaredlockhart** [comment] 2022-01-28 21:39
Until this blocks users I'm closing for now.

**Closed by jaredlockhart** 2022-01-28 21:39 UTC
Labels: [QA]:Major issue, Good First Bug
