### ISSUE TITLE
The "Name" input field validation should not be case sensitive when entering existing experiments name with different cases

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1070] opened 2019-03-19 16:32 UTC
**[Affected versions]:**
- Firefox Release 66.0 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website with the name (eg: the experiment is named "Owner").
- Have a second experiment created on the Experimenter stage website with a different name.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the second created experiment from prerequisites.
3. Click the "Edit" button from "Overview" section.
4. Enter the name from the first created experiment starting with a lowercase (eg.: "owner").
5. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- An error message that informs the user that the name is already used, is displayed.

**[Actual result]:**
- No error message is displayed, the field is wrongly validated (green border), but the the draft is not saved. 

**[Notes]:**
- This issue is not reproducible if the name is inserted with the same cases. 
- Attached is a screen recording of the issue:
![Owner](https://user-images.githubusercontent.com/40061643/54623919-1d9d7c00-4a75-11e9-9940-c18272048a0e.gif)

**Comment by jaredkerim** [comment] 2019-04-02 20:08
Good catch! Super subtle, why isn't the form reporting errors?  This is actually a duplicate of https://github.com/mozilla/experimenter/issues/1129

**Closed by jaredkerim** 2019-04-02 20:08 UTC
Labels: [QA]:Normal issue

**Comment by Softvision-RemusDranca** [comment] 2019-05-13 07:53
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.0 stage deployment.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
