### ISSUE TITLE
Intermittent test failure:  TestVisualizationView.test_analysis_results_view_data_1_Complete

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4475] opened 2021-01-25 19:24 UTC
From: https://app.circleci.com/pipelines/github/mozilla/experimenter/8142/workflows/c0a9d48f-2409-4e1f-a8bd-16f8b5026868/jobs/21443

```
=================================== FAILURES ===================================
_______ TestVisualizationView.test_analysis_results_view_data_1_Complete _______
[gw2] linux -- Python 3.9.1 /usr/local/bin/python

a = (<experimenter.visualization.tests.api.test_views.TestVisualizationView testMethod=test_analysis_results_view_data_1_Complete>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

/usr/local/lib/python3.9/site-packages/parameterized/parameterized.py:533: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/unittest/mock.py:1337: in patched
    return func(*newargs, **newkeywargs)
/usr/local/lib/python3.9/site-packages/parameterized/parameterized.py:81: in dummy_func
    return orgfunc(*args, **kwargs)
/usr/local/lib/python3.9/unittest/mock.py:1337: in patched
    return func(*newargs, **newkeywargs)
experimenter/visualization/tests/api/test_views.py:140: in test_analysis_results_view_data
    self.assertEqual(FULL_DATA, json_data)
E   AssertionError: {'daily': [{'point': 12, 'upper': 13, 'lowe[7049 chars]alse} != {'show_analysis': False, 'daily': [{'point'[5961 chars]}}}}}
E   Diff is 27869 characters long. Set self.maxDiff to None to see it.

----------- coverage: platform linux, python 3.9.1-final-0 -----------
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-872)
┆Issue Number: EXP-872

**Comment by data-sync-user** [comment] 2021-01-28 01:28
➤ Les Orchard commented:

Tried running this locally a pile of times and haven't seen it fail. Guessing it has something to do with randomized sample Experiment data, but unsure what in particular to induce the failure predictably.

We might want to add a `maxDiff = None` to this test for the next time it fails, because this means that diagnostic information to figure out the problem has been obscured:

Diff is 27869 characters long. Set self.maxDiff to None to see it.

**Comment by data-sync-user** [comment] 2021-01-28 17:43
➤ Les Orchard commented:

Ran this test repeatedly overnight in a loop on my local machine hoping to trigger a failure. No failure occurred.

Thinking that suggests my machine does not reproduce the failure condition present in CI. Or, maybe we incidentally fixed it since this issue was filed.

Best next step I can think of is to enable fuller diff output to catch more information (i.e. a randomized field) if/when this happens again:

https://github.com/mozilla/experimenter/pull/4491 ( https://github.com/mozilla/experimenter/pull/4491 )

Also thinking it might be worth closing this issue and reopening if/when it happens again.

**Comment by data-sync-user** [comment] 2021-01-28 17:44
➤ Les Orchard commented:

Oh, looks like this was also addressed by disabling the test? Didn't see a reference to that in this issue, but this seems related?

https://github.com/mozilla/experimenter/pull/4479/files ( https://github.com/mozilla/experimenter/pull/4479/files )

But, the test is not disabled in my local check-out, so my overnight run was running the test

**Comment by data-sync-user** [comment] 2021-01-28 18:14
➤ Les Orchard commented:

We resolved this issue in the short term by disabling the test. Going to kick this back into the backlog.

But, for future investigation, I managed to get one CI test run with a fuller diff of the failed assertion that might be useful:

https://app.circleci.com/pipelines/github/mozilla/experimenter/8197/workflows/b5ea43c2-bbe9-47eb-a7b3-cc499bf21a2e/jobs/21683 ( https://app.circleci.com/pipelines/github/mozilla/experimenter/8197/workflows/b5ea43c2-bbe9-47eb-a7b3-cc499bf21a2e/jobs/21683 )

Looks like an unexpected extra branch in the DB?

...

E - 'mandatory-multi-tasking-adapter_ever_used': {'absolute': {'all': [{'count': 48,
E - 'lower': 2,
E - 'point': 4,
E - 'upper': 8}],
E - 'first': {'count': 48,
E - 'lower': 2,
E - 'point': 4,
E - 'upper': 8,}}
E - 'difference': {'all': [],
E - 'first': {,}}
E - 'relative_uplift': {'all': [],
E - 'first': {},}}
E 'persistent-methodical-matrices_ever_used': {'absolute': {'all': [{'count': 48,
E 'lower': 2,
E 'point': 4,
E 'upper': 8}],
E 'first': {'count': 48,
E 'lower': 2,
E 'point': 4,
E 'upper': 8,}}
E 'difference': {'all': [],
E 'first': {,}}
{{}}

**Comment by data-sync-user** [comment] 2021-01-28 18:23
➤ Les Orchard commented:

Just going to close this in favor of a follow up https://jira.mozilla.com/browse/EXP-881

**Closed by data-sync-user** 2021-01-28 18:23 UTC
