### ISSUE TITLE
Results relative branch comparison weekly table - bug in specific prod experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6120] opened 2021-08-04 18:03 UTC
I poked around in production after #6010 was merged and things looked good to me, but in looking at #6071 / EXP-1404, I poked around even more, and there's definitely a bug in at least this experiment if you click to expand the weekly data tables:

https://experimenter.services.mozilla.com/nimbus/multi-stage-onboarding-ask-and-show-to-pin/results#results_summary

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1581)

**Comment by LZoog** [comment] 2021-08-05 20:15
After some digging, it appeared like this experiment somehow had the control branch incorrectly set since the control branch viz data from the API endpoint contained relative uplift branch comparison data which didn't make sense; relative branch comparison data on the control branch shouldn't exist since the comparison is relative to the control branch.

After conferring with Anna S./Rob H., we discovered that while in the experiment data the control/reference branch is set to `control-no-show`, this was overridden to become `msw_control` [in the Jetstream config](https://github.com/mozilla/jetstream-config/blob/59ebb94e672c7a62d7d89b39a9c423241348863d/multi-stage-onboarding-ask-and-show-to-pin.toml#L11). The viz API endpoint returns data with an `is_control` boolean which references what the experiment data is set to, but doesn't reflect the override any overrides by the Jetstream config, which apparently [happens often](https://github.com/mozilla/jetstream-config/search?q=reference_branch).

Since I wasn't sure what the problem was at first, I copied the entire server response from the viz API endpoint and the Experiment data and stuck it in Storybook. I never planned on opening a PR for this since the viz data is 43k lines long, but I did [push it up](https://github.com/mozilla/experimenter/compare/results-page-storybook-xl-data) (which I think I'll leave upstream in case I/someone else ever want to test a large data set on this page) to share Storybook stories. [Here's](https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/46d8ef0d112f816a110dbff3111d01aa3afb1f5a/nimbus-ui/index.html?path=/story/pages-results--with-xl-data-set) what it looks like in prod today, and [here's](https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/8802a69f9794a4e014a1323edc02932b31fa08ab/nimbus-ui/index.html?path=/story/pages-results--with-xl-data-set) what it looks like if the correct control branch is referenced.

We could band-aid this problem by manually changing the control branch to match the Jetstream config control branch, but this problem will come up again. We're going to fix this in #6129, and once that's complete, this issue will be fixed.

I'm going to mark this as a dupe of #6129 / EXP-1587 or a spike and close this out.

**Closed** 2021-08-05 20:18 UTC
Labels: Visualization
