### ISSUE TITLE
N+1 Query

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9203] opened 2023-08-02 18:23 UTC
Sentry Issue: [EXPERIMENTER-PROD-HK](https://mozilla.sentry.io/issues/4359963523/?referrer=jira_integration)
| **Offending Spans** | db - SELECT "experiments_nimbusversionedschema"...

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3732)

**Comment by brennie** [comment] 2023-08-05 03:57
I think this is a dupe of #9202 but I'm not sure. They are both due to NimbusVersionedSchema queries not being prefetched in the API,

**Comment by jaredlockhart** [comment] 2023-08-11 18:54
Fixed in https://github.com/mozilla/experimenter/issues/9202

**Closed by jaredlockhart** 2023-08-11 18:54 UTC
Labels: Duplicate
