### ISSUE TITLE
Link data science bug to Experimenter

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#978] opened 2019-02-26 23:49 UTC
When someone links a data science bug to Experimenter, it would be great if Experimenter could link that data science bug back to Experimenter.

If [this change](https://bugzilla.mozilla.org/show_bug.cgi?id=1526090) (or [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=577847)) lands, the "See Also" field would be a great way to link them.

In the interim, Experimenter could just leave a comment.

**Comment by jaredkerim** [comment] 2019-02-27 15:40
@shell1 This sounds like a v3 thing, is this a duplicate of an existing bug or should we add it to the bugzilla column?

**Comment by shell1** [comment] 2019-02-27 17:04
This makes sense.  Pulling this to look at when we do the other bugzilla work.  That is planned towards the end of v3 - so it's a while out.

**Comment by shell1** [comment] 2019-04-26 16:37
covering as we included the data science bug in "see also" during the "ready for sign-offs" bugzilla update #802

**Closed by shell1** 2019-04-26 16:37 UTC
Labels: Workers
