### ISSUE TITLE
A "Server Error (500)" error is displayed if the "Save Sign-Offs" button is clicked after the login session expires

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/experimenter#882] opened 2019-02-06 15:46 UTC
**[Notes]:**
- Even if the fix for the issue 247 will change the session duration from ~30 minutes to 24 hours, we will still encounter this issue and we will need to navigate again to the "Experimenter" website in order to use it.

**[Affected versions]:**
- Firefox Release 65.0 and above
- Chrome 72.0.3626.81

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter-app.dev.mozaws.net/" website.
- You are logged with your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter-app.dev.mozaws.net/".
2. Open the experiment from prerequisites and click the "Ready for Sign-Off" button.
3. Wait for ~30 minutes and click the "Save Sign-Offs" button.
4. Observe the behavior.

**[Expected result]:**
- You are re-logged and the recent changes are saved.

**[Actual result]:**
- A "Server Error (500) error is displayed after you are re-logged.

**[Additional notes]:**
- The error is still displayed after refreshing the page.
- Also if you click the browser's "Back" button, you are prompted with the login screen. However, if you will decide to log in again the operation will fail.
- This issue is not reproducible if you navigate to the "Experimenter" website again.
- Attached is a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/52351912-50932f80-2a34-11e9-92d3-f60cb6e50d1d.gif)

**Comment by jaredkerim** [comment] 2019-02-07 19:10
Closing as a duplicate of #881

**Closed by jaredkerim** 2019-02-07 19:10 UTC
Labels: [QA]:Major issue
