### ISSUE TITLE
design doc links not per experiment - seems to be all

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#7742] opened 2022-09-13 22:49 UTC
way to many link showing up - looking at this experiment https://experimenter.services.mozilla.com/nimbus/pocket-newtab-send-to-pocket-2/results

![image](https://user-images.githubusercontent.com/8192232/190022755-c9359de6-cc8d-4685-86de-b7c3e7afb404.png)

**Comment by jaredlockhart** [comment] 2022-09-14 15:00
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/7739

**Closed by jaredlockhart** 2022-09-14 15:00 UTC
