### ISSUE TITLE
Add client-side validation with error message to disallow negative numbers for all Audience fields

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4615] opened 2021-02-12 21:23 UTC
Expected Number of Clients will show a helpful error message when it is invalid for the case where the value is not a number:

<img width="480" alt="Screen Shot 2021-02-12 at 4 23 22 PM" src="https://user-images.githubusercontent.com/119884/107823963-a818b400-6d4e-11eb-94f4-185abcfbbfae.png">

but not for the case where the value is negative:

<img width="477" alt="Screen Shot 2021-02-12 at 4 22 16 PM" src="https://user-images.githubusercontent.com/119884/107823987-b070ef00-6d4e-11eb-9541-3a494bfc0362.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-956)
┆Issue Number: EXP-956

**Comment by LZoog** [comment] 2021-02-12 21:25
This is a dupe of #4276, I'll add a comment over there to add helpful messaging

**Comment by LZoog** [comment] 2021-02-12 21:32
Hmmm so #4276 is related but the actual issue reported there is that you could _save_ the negative number and that's different than adding client-side validation.

I'm reopening this and closing the other. Though, **we should also enforce this rule on other Audience fields, not _just_ number of clients.**

**Comment by lmorchard** [comment] 2021-02-25 23:16
> we should also enforce this rule on other Audience fields, not just number of clients.

Unless I'm missing something, I think this is already covered on the server-side. I can't reproduce being able to set other negative values in the GQL mutation.

The `population_percent` field was given a positive value constraint here: https://github.com/mozilla/experimenter/commit/69e3bafe9c8db49d4ff4f4f673b81bad2db59ddd

The rest of the fields use `PositiveIntegerField`: https://github.com/mozilla/experimenter/blame/main/app/experimenter/experiments/models/nimbus.py#L35-L44

**Closed** 2021-02-26 16:04 UTC
Labels: quick-win
