### ISSUE TITLE
Controlling & Visualizing Interactions - Automates the manual effort of determining conflicting experiments on populations.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5652] opened 2021-06-21 08:39 UTC
Automates the manual effort of determining conflicting experiments on populations.

**Why?**

* Important for Search and New Tab
* Important for First Run
* Evidence of failures caused in Normandy, identified as a long held risk

**KR**

Velocity, and Reliability (not a KR, but important long term)

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/EXP-1136)

**Comment by jaredlockhart** [comment] 2022-01-28 20:41
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/6171

**Closed by jaredlockhart** 2022-01-28 20:41 UTC
Labels: Request
