### ISSUE TITLE
API Documentation is broken

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3804] opened 2020-10-22 17:18 UTC
I'm seeing this:

<img width="1636" alt="Screen Shot 2020-10-22 at 1 17 44 PM" src="https://user-images.githubusercontent.com/119884/96907335-187e8b00-1469-11eb-84ff-8327da401341.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-515)
┆Issue Number: EXP-515

**Comment by jaredlockhart** [comment] 2020-10-22 17:24
Oh weird, after 30s it shows up:

<img width="1633" alt="Screen Shot 2020-10-22 at 1 24 27 PM" src="https://user-images.githubusercontent.com/119884/96907933-ede10200-1469-11eb-817b-e2be6ac39dfe.png">

**Comment by tiftran** [comment] 2020-10-22 23:27
closing since it seems like it can longer be reproduce

**Closed by tiftran** 2020-10-22 23:27 UTC
Labels: API, Defect, Legacy
