### ISSUE TITLE
"Add Comment" link is failing

### ISSUE THREAD

**Issue by arthuredelstein** [mozilla/experimenter#2616] opened 2020-05-01 22:54 UTC
I tried to click "Add Comment" on a Rollout but nothing happened. In the console I see
`TypeError: can't convert n to string`.

![image](https://user-images.githubusercontent.com/355566/80847322-0c092c00-8bc4-11ea-95f9-93564d1f38c9.png)

**Comment by jaredlockhart** [comment] 2020-05-02 21:55
Looks like a duplicate of https://github.com/mozilla/experimenter/issues/2614

**Closed by jaredlockhart** 2020-05-02 21:55 UTC
