### ISSUE TITLE
[Feature request] Add capability to "watch" experiments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6009] opened 2021-07-20 18:56 UTC
Add capability to have people subscribe or watch experiments that they didn't launch. 

Often there are several people who are helping with experiments, and it'd be nice to have the capabiility to receive updates on the experiment even if you're not the one launching the experiment.

┆Issue is synchronized with this [Jira EXP Request](https://mozilla-hub.atlassian.net/browse/EXP-1518)

**Comment by jaredlockhart** [comment] 2021-08-20 21:04
Closing as dupe of https://github.com/mozilla/experimenter/issues/5588

**Closed by jaredlockhart** 2021-08-20 21:04 UTC
