### ISSUE TITLE
Save and Continue seems unnecessarily disabled on Audience page?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4660] opened 2021-02-19 17:34 UTC
Filling in the Audience page, the `Save and Continue` button is disabled even if I've filled out the form:

<img width="1286" alt="Screen Shot 2021-02-19 at 12 35 06 PM" src="https://user-images.githubusercontent.com/119884/108540228-ecf09d80-72ae-11eb-9abc-59edfab70804.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-984)
┆Issue Number: EXP-984

**Comment by data-sync-user** [comment] 2021-02-19 17:40
➤ Wil Clouser commented:

Duplicate of https://jira.mozilla.com/browse/EXP-976

**Closed** 2021-02-19 17:40 UTC
