### ISSUE TITLE
Intermittent testure failure: TestNimbusReadyForReviewSerializer::test_valid_experiment_minimum_population_percent

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6051] opened 2021-07-23 16:40 UTC
In CI:

```java
=================================== FAILURES ===================================
_ TestNimbusReadyForReviewSerializer.test_valid_experiment_minimum_population_percent _
[gw1] linux -- Python 3.9.6 /usr/local/bin/python3

self = <experimenter.experiments.tests.api.v5.test_serializers.TestNimbusReadyForReviewSerializer testMethod=test_valid_experiment_minimum_population_percent>

    def test_valid_experiment_minimum_population_percent(self):
        experiment = NimbusExperimentFactory.create_with_lifecycle(
            NimbusExperimentFactory.Lifecycles.CREATED,
            population_percent=0.0001,
        )
        serializer = NimbusReadyForReviewSerializer(
            experiment,
            data=NimbusReadyForReviewSerializer(
                experiment,
                context={"user": self.user},
            ).data,
            context={"user": self.user},
        )
>       self.assertTrue(serializer.is_valid())
E       AssertionError: False is not true
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1541)

**Comment by jaredlockhart** [comment] 2021-07-23 16:40
Prolly a dupe of https://github.com/mozilla/experimenter/issues/6044

**Comment by jaredlockhart** [comment] 2021-07-26 16:27
I'm going to close this as a dupe of #6044 and if we see it again we can refile.

**Closed by jaredlockhart** 2021-07-26 16:27 UTC
