### ISSUE TITLE
TypeError: c is null

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8256] opened 2023-02-03 23:07 UTC
Sentry Issue: [EXPERIMENTER-PROD-GF](https://sentry.io/organizations/mozilla/issues/3915920545/?referrer=jira_integration)

```
TypeError: c is null
  at formControlAttrs (hooks/useCommonForm/useCommonFormMethods.tsx:55:31)
  at <object>.formControlAttrs (hooks/useCommonForm/useCommonNestedForm.tsx:44:8)
  at FormBranch (components/PageEditBranches/FormBranches/FormBranch.tsx:111:19)
  at sentryWrapped (../../../src/helpers.ts:98:17)
  at requestAnimationFrame (../../../../src/integrations/trycatch.ts:131:21)
...
(45 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3132)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33650">image-20230203-230736.png</a>

**Comment by data-sync-user** [comment] 2023-02-03 23:08
➤ Elise Richards commented:

When you click on the Branches page it will not render - https://experimenter.services.mozilla.com/nimbus/window-modal-vs-tab-modal/edit/branches ( https://experimenter.services.mozilla.com/nimbus/window-modal-vs-tab-modal/edit/branches )

!image-20230203-230736.png|width=556,height=264!

**Comment by jaredlockhart** [comment] 2023-02-09 18:12
Closing as a dupe of https://github.com/mozilla/experimenter/issues/8240

**Closed by jaredlockhart** 2023-02-09 18:12 UTC
