### ISSUE TITLE
Include operating system filter in Normandy recipe serializers

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1771] opened 2019-10-18 19:38 UTC
We need to include the operating system filter somewhere in the Normandy Recipe serializers.  I don't think there's a first class filter object for it so it'll have to go in the 'additional filter expressions' field.

**Comment by mythmon** [comment] 2019-10-18 19:46
Dupe of #1770

**Closed by mythmon** 2019-10-18 19:46 UTC
Labels: API, Defect, P1 - High Priority
