### ISSUE TITLE
"Server Error (500)" error is displayed when the "archive this experiment" option is clicked

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/experimenter#784] opened 2019-01-14 17:24 UTC
[Affected versions]:
Chrome 71.0.3578.98

[Affected Platforms]:
Windows 10

[Prerequisites]:
Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
You are logged in your LDAP account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment.
3. Click on "Archive this experiment".
4. Observe the behavior.

[Expected result]:
The experiment is archived.

[Actual result]:
The "Server Error (500)" error is displayed.

[Notes]:
Tested on Firefox, Opera and Edge and wasn't reproducible. This issue is ONLY reproducible on Chrome.

Attached is a screen recording of the issue:
![experimenter - stage - archive exp error](https://user-images.githubusercontent.com/44404741/51128663-35534c80-1807-11e9-85ff-177bbb6fff49.gif)

**Comment by jaredkerim** [comment] 2019-02-05 21:20
@LucianaQueirolo I was not able to reproduce this, can you verify this is still happening?

**Comment by jaredkerim** [comment] 2019-02-07 19:10
Oh I see, it's a duplicate of #881

**Closed by jaredkerim** 2019-02-07 19:10 UTC
Labels: Bug
