### ISSUE TITLE
Can't add feature configs to branches

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4229] opened 2020-12-11 12:48 UTC
When I tried to add a feature config to branches on /edit/branches, nothing happens. No console errors
![SeFWFCWcbi](https://user-images.githubusercontent.com/1455535/101905301-3a50e000-3b85-11eb-8aa8-2de691403048.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-741)
┆Issue Number: EXP-741

**Comment by k88hudson** [comment] 2020-12-11 20:22
Weirdly, this also seemed to *remove* the feature config even though it was added in django admin

**Comment by data-sync-user** [comment] 2020-12-11 20:23
➤ Chelsea Lewis commented:

Dupe of EXP-735.

**Comment by pdehaan** [comment] 2020-12-11 21:07
Ref: #4219

**Closed by pdehaan** 2020-12-11 21:07 UTC
