### ISSUE TITLE
Experiment runs back in time

### ISSUE THREAD

**Issue by travis79** [mozilla/experimenter#4234] opened 2020-12-11 17:40 UTC
Looking at the "Live" page for the staging experiment "fenix-nimbus-validation-2" I see that it is set to run to Dec 31, 1969.

![Screen Shot 2020-12-11 at 11 37 33 AM](https://user-images.githubusercontent.com/7341315/101936065-ad6a4e80-3ba5-11eb-93f3-b7dd3554fb69.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-744)
┆Issue Number: EXP-744

**Comment by pdehaan** [comment] 2020-12-11 17:56
Probably a dupe of #4206; _"Live experiment has an endDate of `null` which reports as "Dec 31, 1969" on front end"_ ([EXP-728](https://jira.mozilla.com/browse/EXP-728))

**Comment by LZoog** [comment] 2021-01-29 19:18
Closing this, should have been fixed in #4337

**Closed by LZoog** 2021-01-29 19:18 UTC
