### ISSUE TITLE
Add validators for different feature types

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3289] opened 2020-08-25 13:41 UTC
We have schemas available for about:welcome, CFR, and moments. Let's add a validation step for the JSON value field.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-63)
┆Issue Number: EXP-63

**Comment by data-sync-user** [comment] 2020-11-03 21:33
➤ Jared Kerim commented:

Duplicate of https://jira.mozilla.com/browse/EXP-510

**Closed by data-sync-user** 2020-11-03 21:32 UTC
