### ISSUE TITLE
Saving on branch page does not update missing details in side bar

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5273] opened 2021-05-18 21:07 UTC
Steps to reproduce

1) Fill out the branches page with name/description but not feature
2) Hit save
3) Navigate to review page, find message about missing details on branch page
4) Navigate to branch page, select a feature, hit save
5) Sidebar still shows 'missing details in branches'

Expected results:
'Missing details' should go away after I save

<img width="1512" alt="Screen Shot 2021-05-18 at 5 06 17 PM" src="https://user-images.githubusercontent.com/119884/118723550-90444680-b7fb-11eb-92f4-4e360de8c496.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1331)
┆Issue Number: EXP-1331

**Comment by LZoog** [comment] 2021-05-18 21:29
This is basically a dupe of #5103 / same screenshot/issue I had in #5171

**Closed** 2021-06-17 20:39 UTC
Labels: Orphaned
