### ISSUE TITLE
Autopopulate the Control branch name to: "Control"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4802] opened 2021-03-12 02:34 UTC
We should try to auto-populate the control branch name to "Control". It seems like most experiments have been naming the control branch "Control" and it might reduce friction, time, and effort while designing the experiment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1064)
┆Issue Number: EXP-1064

**Comment by data-sync-user** [comment] 2021-03-12 13:29
➤ Jody Heavener commented:

This might be do-able in EXP-978

**Comment by LZoog** [comment] 2021-04-01 17:54
Closing as a dupe of #4959

**Closed by LZoog** 2021-04-01 17:54 UTC
Labels: quick-win
