### ISSUE TITLE
Summary/review table shows extra "not set" branch with only one branch saved

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4403] opened 2021-01-11 21:25 UTC
If I create a new experiment, hit the branches form, delete the second empty branch, and just create a control branch, save, navigate away, then navigate back, it re-adds the second empty branch on top of the control branch I saved.  This could be confusing for experiments that are designed to only have a single branch.

Also on the review page, it shows the second unsaved branch as being incomplete:

<img width="1144" alt="Screen Shot 2021-01-11 at 4 24 00 PM" src="https://user-images.githubusercontent.com/119884/104240074-7cda3680-5429-11eb-9bc4-6fec08ea0b2c.png">

You should be able to create an experiment with only a single branch and have that be the only branch saved/displayed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-821)
┆Issue Number: EXP-821

**Comment by jaredlockhart** [comment] 2021-01-11 21:26
It doesn't show up in the recipe so that party's correct:


```json
  "branches": [
    {
      "slug": "c",
      "ratio": 1
    }
  ],
```

**Comment by LZoog** [comment] 2021-05-18 22:23
This is kind of a dupe of #4403 but since this issue also mentions the summary table, I'll leave them both open and close them in one PR and consider this issue the summary page issue and the former the one that deals with the form.

**Closed** 2021-05-20 14:23 UTC
Labels: quick-win
