### ISSUE TITLE
Experimenter (stage and production) always prompts me to log in after a few page views

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#769] opened 2019-01-09 23:05 UTC
If I go to https://experimenter.services.mozilla.com/ and click the "Mozilla Experimenter" in the header a few times, it always prompts me to log in.

Even if I'm on the homepage and apply the current filters a couple times (without changing anything), it sends me back to the auth0 login site and forces me to log in again.

**Comment by jaredkerim** [comment] 2019-02-05 21:09
Yeah the sessions only last for an hour I think, I've asked ops about this and they've been hesitant so I think we need to be more persistent.  Also this is a duplicate of #247

**Closed by jaredkerim** 2019-02-05 21:09 UTC
