### ISSUE TITLE
Remove "US users (en)" from Advanced Targeting?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6077] opened 2021-07-28 01:26 UTC
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-2021-07-27-audiences-gonna-audience/edit/audience

In the "Advanced Targeting" you can select "US users (en)" from the drop down menu. But now that we have "Locales" and "Languages", that is a bit redundant and potentially confusing.

For example, with NO advanced targeting, my fake study's JEXL targeting expression looks like:

```jexl
'app.shield.optoutstudies.enabled'|preferenceValue &&
    locale in ['ast', 'bs', 'en-CA', 'en-GB', 'en-US', 'es-MX', 'he', 'nb-NO'] &&
    region in ['AF', 'AS', 'AX', 'BQ', 'CA', 'CD', 'CI', 'MP', 'PR', 'PS', 'RE', 'SH', 'UM', 'US', 'VI']
```

If I set Advanced Targeting to "US users (en)", my `jexlTargetingExpression` changes to the following:

```diff
'app.shield.optoutstudies.enabled'|preferenceValue &&
+   localeLanguageCode == 'en' &&
+   region == 'US' &&
    locale in ['ast', 'bs', 'en-CA', 'en-GB', 'en-US', 'es-MX', 'he', 'nb-NO'] &&
    region in ['AF', 'AS', 'AX', 'BQ', 'CA', 'CD', 'CI', 'MP', 'PR', 'PS', 'RE', 'SH', 'UM', 'US', 'VI']
```

But now that we're enforcing that `region` is exactly 'US', the `region in ['AF', 'AS', 'AX', 'BQ', 'CA', 'CD', 'CI', 'MP', 'PR', 'PS', 'RE', 'SH', 'UM', 'US', 'VI']` will be redundant since we already checked for `region` above.

But also, if we do remove it, we have to watch for the case of past experiments that used that `targetingConfigSlug` and gracefully handle it.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/EXP-1555)

**Comment by jaredlockhart** [comment] 2021-07-28 15:18
Yep!  Closing as a duplicate of https://github.com/mozilla/experimenter/issues/6034

**Closed by jaredlockhart** 2021-07-28 15:18 UTC
