### ISSUE TITLE
Next Button should also save when clicked

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4266] opened 2020-12-14 21:54 UTC
A few users had clicked Next in the UI expecting that it would Save their data, and were surprised that there was data loss. 

As a user, I want to be able to save my data and avoid data loss if I click Next in the UI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-753)
┆Issue Number: EXP-753

**Comment by lmorchard** [comment] 2020-12-14 23:51
Duplicate of https://github.com/mozilla/experimenter/issues/4022 ?

**Comment by jodyheavener** [comment] 2020-12-15 00:04
Yeah, it's cancelled in Jira but not updating here (Wil is trying to fix that)

**Closed by jodyheavener** 2020-12-15 00:04 UTC
