### ISSUE TITLE
Support Markdown formatting?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#893] opened 2019-02-07 19:00 UTC
Re: https://experimenter.services.mozilla.com/experiments/activity-stream-pkt-newtab-beta66smoketest1/

I randomly spotted some unparsed Markdown in a few places...

Like the following in the overview:

```
[Description of Branches](https://docs.google.com/document/d/11JjU5V_kvgwb-ou9yZBKp3nfPaQtSDO3wHZXclAGT8k/edit#heading=h.j25ryht7flvo)
```

Or the following inline code blocks in the populations section:

```
- `browser.newtabpage.enable`
- `browser.startup.homepage`
- `browser.newtabpage.activity-stream.showSearch`
- `browser.newtabpage.activity-stream.feeds.topsites`	
- `browser.newtabpage.activity-stream.feeds.section.topstories`
- `browser.newtabpage.activity-stream.feeds.section.highlights`

* please exclude any users that have the Mozilla Dark Theme activated: `['environment']['addons']['activeAddons']['theme']['id']` is `'firefox-compact-dark@mozilla.org'`
```

**Comment by jaredkerim** [comment] 2019-02-27 16:12
Closing as a duplicate of #84 and #326

**Closed by jaredkerim** 2019-02-27 16:12 UTC
