### ISSUE TITLE
General Application Error in Summary results

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5914] opened 2021-07-08 17:36 UTC
In a live experiment on prod, 

https://experimenter.services.mozilla.com/nimbus/default-browser-adoption-experiment-release/results#default-browser

The results page shows 

!Screen Shot 2021-07-08 at 1.34.03 PM.png|thumbnail! 

Sentry error for this is:

https://sentry.prod.mozaws.net/operations/nimbus-ui-prod/issues/11722096/?query=is%3Aunresolved

Network shows data being returned from the backend so the error is probably in the frontend.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1470)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15580/Screen+Shot+2021-07-08+at+1.34.03+PM.png">Screen Shot 2021-07-08 at 1.34.03 PM.png</a>

**Comment by jaredlockhart** [comment] 2021-07-08 17:39
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/5828

**Closed by jaredlockhart** 2021-07-08 17:39 UTC
