### ISSUE TITLE
Changing bugzilla ticket to use public name and public description

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2656] opened 2020-05-12 18:04 UTC
public name and description hadn't been required before - but are now required for all except rollouts.

- could we replace internal name with public name?  Just use public name?  I believe private names were only used because activity stream needed to start with activity stream.  Other reason.  Verify with activity stream and if Jared can think if this is still needed.  Even if it is - it's not the worse thing to have that.  Would change how the ticket is handled - as right not it appends versions to the bugzilla ticket name - and that could stop.  Jared explained just changing the wording that is visible instead of swapping fields.
- Could we put the public description on the bugzilla tickets - and just replace description from rollouts with public description?  Since it is public in the sense that it goes in a bugzilla ticket.
- rename internal description - detailed description

**Comment by jaredlockhart** [comment] 2020-05-19 20:14
Closing as a duplicate of #2653

**Closed by jaredlockhart** 2020-05-19 20:14 UTC
