### ISSUE TITLE
Nimbus UI search box content not stored in URL

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8243] opened 2023-02-03 16:28 UTC
We should store the search query on the landing page in the URL like we do for the other filters so that when you hit back it goes back to the page you were on, or you can share the search results you're seeing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3127)

**Comment by cy-moi** [comment] 2023-03-06 23:23
Hi, I'm an outreachy intern. I would like to work on this issue if it is ok @yashikakhurana

**Comment by yashikakhurana** [comment] 2023-03-06 23:29
thanks @cy-moi for your interest, the issue is assigned to you

**Comment by cy-moi** [comment] 2023-03-07 04:27
#8418

**Closed** 2023-03-13 18:31 UTC
Labels: Outreachy
