### ISSUE TITLE
There is no "Platform" section/field available in order to select the experiment's targeted platforms

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#940] opened 2019-02-15 13:29 UTC
**[Notes]:**
- The "Platforms" section/field should include: Mac, Windows, Linux, Mobile and also it should be mandatory, because QA generally has to follow up with emails regarding the targeted platforms if no information is provided on this matter. 

**[Affected versions]:**
- Firefox Release 65.0.1 and above
- Chrome 72.0.3626.109

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Edit" button from "Population" section.
3. Observe the sections/fields from "Population" page.

**[Expected result]:**
- A section/field for the targeted "Platforms" is displayed.

**[Actual result]:**
- There is no section/field for targeted "Platforms" displayed.

**[Additional Notes]:**
- This issue is reproducible on all Experimenter websites (dev., stage and production).
- This issue is also reproducible when creating a new experiment after you complete the "Overview" page and continue to the "Population" page.
- Attached is a screen shot with the default sections/fields of the "Population" page: 
![screenshot_2019-02-15 mozilla experimenter](https://user-images.githubusercontent.com/40061643/52859754-37763700-3136-11e9-8788-d611a89714dd.png)

**Comment by shell1** [comment] 2019-02-22 01:04
There is a bug to make the whole Population Filtering section individual entry fields with multi-select list options (when applicable).  That will make moving this configuration into Normandy easier and less error prone.  #739 bug shouldn't be more than a month out from being started.

**Comment by jaredkerim** [comment] 2019-02-27 15:45
I will close this as a duplicate of #739.

**Closed by jaredkerim** 2019-02-27 15:45 UTC
