### ISSUE TITLE
Add all statuses as directory view tabs

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5954] opened 2021-07-14 19:08 UTC
On the Nimbus directory page, we currently have the following tabs:

Active | Completed | Drafts

where Active has the three subheadings: Live, In Review, In Preview

Let's reorganize that into the following tabs in the following order:

Live | Review | Preview | Draft | Complete

with no subheadings under any tab.

The first column of each tabs table is currently labeled the same as the tab name so let's change the title of the first column to `Name`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1490)

**Comment by jodyheavener** [comment] 2021-07-14 19:11
@jaredlockhart dupe of https://github.com/mozilla/experimenter/issues/5609

**Closed** 2021-07-21 13:32 UTC
