### ISSUE TITLE
Nimbus experiments need Draft->Review->Live->Complete breadcrumby UI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4068] opened 2020-11-20 21:11 UTC
Per [Figma specs](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216066%3A11123)

# Expected
![Nimbus_Console_UI_–_Figma](https://user-images.githubusercontent.com/557895/99846270-df4e3f00-2b2a-11eb-921f-f91811848464.png)

# Actual
![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99847522-1160a080-2b2d-11eb-82f4-d244ba814230.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-643)
┆Issue Number: EXP-643

**Comment by data-sync-user** [comment] 2020-11-20 21:17
➤ Jody Heavener commented:

Dupe of EXP-467

**Closed** 2020-12-02 18:55 UTC
