### ISSUE TITLE
Wrong duration displayed

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5434] opened 2021-06-15 19:10 UTC
Just noticed we're still showing the wrong duration in one place, that 28 should be 0:

<img width="1192" alt="Screen Shot 2021-06-15 at 3 09 29 PM" src="https://user-images.githubusercontent.com/119884/122109786-c15c6a80-cdeb-11eb-9e7a-c5e4e7d5bc97.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1423)
┆Issue Number: EXP-1423

**Comment by lmorchard** [comment] 2021-06-15 19:39
Is this a dupe of #4945? PR #5402 should aim to address this

**Closed** 2021-06-17 20:37 UTC
Labels: Orphaned
