### ISSUE TITLE
Some results not showing up for iOS experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6375] opened 2021-09-07 15:58 UTC
There are some metrics that are not showing up as part of the final experiment results for this experiment https://experimenter.services.mozilla.com/nimbus/default-browser-onboarding/results#results_summary (there are more displayed in the "detailed analysis"/partybal page)

From talking with Anna she mentioned that it's an Experimenter front end issue. We are mostly concerned with these metrics

* exposure
* onboarding card interactions (clicking "Dismiss" or "Go to settings")

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1732)

**Comment by data-sync-user** [comment] 2021-09-08 19:05
➤ Jared Kerim commented:

Kimberly Siegler Thank you for filing 🙂  Unfortunately exposure metrics aren’t yet supported in the Nimbus Results page.

For the other metrics you mentioned, can you show me where those are defined for the experiment? An outcome? A custom jetstream config?

**Comment by jaredlockhart** [comment] 2022-02-04 20:37
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/7029

**Closed by jaredlockhart** 2022-02-04 20:37 UTC
