### ISSUE TITLE
Allow partial submission for all mutations except create

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4292] opened 2020-12-17 16:43 UTC
Each of the four mutations:

 

Overview

Branches

Metrics

Audience

 

should allow for partial submission, ie any subset of fields.  Fields should only be required in the readyForReview check, not at form save time.  This change is scoped only to the backend.

https://jira.mozilla.com/browse/EXP-770

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-775)
┆Issue Number: EXP-775

**Comment by data-sync-user** [comment] 2021-01-04 20:01
➤ Jared Kerim commented:

Closing as a duplicate of https://jira.mozilla.com/browse/EXP-770

**Closed by data-sync-user** 2021-01-04 20:01 UTC
