### ISSUE TITLE
Update DTO (recipe) to support multiple feature configs in a single experiment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6176] opened 2021-08-11 13:44 UTC
Example:

```
{
  featureIds: ["foo", "bar"],
  branches: [{
    slug: "control",
    ratio: 1
    features: [
        {
          featureId: "foo",
          value: {enabled: true}
        },
        {
          featureId: "bar",
          value: {whatever: "hi"}
        }
    ],
  }]
}
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1613)

**Comment by data-sync-user** [comment] 2021-08-11 13:47
➤ Kate Hudson commented:

We could either change the format to be more concise: 

Version 1

{
  featureIds: ["foo", "bar"],
  branches: [{
    slug: "control",
    ratio: 1
    features: {
      foo: {enabled: true},
      bar: {whatever: "hi"}
    }
  }]
}Or go with something that minimizes the changes we’d have to make on the client (i.e. the type of FeatureConfig stays the same, you just get an array of them:

Version 2

{
  featureIds: ["foo", "bar"],
  branches: [{
    slug: "control",
    ratio: 1
    features: [
        {
          featureId: "foo",
          value: {enabled: true}
        },
        {
          featureId: "bar",
          value: {whatever: "hi"}
        }
    ],
  }]
}Victor Andrei Oprea Travis Long any thoughts about whether Version 1 is going to be a significant amount of work / make it harder to do backwards compatibility v.s. Version 2? I’m leaning towards the latter just because it’s fewer tests/less code to update

**Comment by data-sync-user** [comment] 2021-08-11 20:42
➤ Victor Andrei Oprea commented:

I agree, I think it’s easier to adjust the code for features as array, I also personally prefer working with arrays over arbitrary object keys.

**Comment by data-sync-user** [comment] 2021-08-16 16:02
➤ Kate Hudson commented:

Ok, let’s go with the array-based version.

**Comment by jaredlockhart** [comment] 2022-01-28 20:30
Closing as a dupe of #6728

**Closed by jaredlockhart** 2022-01-28 20:30 UTC
Labels: Enhancement
