### ISSUE TITLE
Remove extra space from the overview section

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#8432] opened 2023-03-07 23:11 UTC
There is some extra spaces on the overview page, it would be good to have things aligned
![Screenshot 2023-03-07 at 3 08 58 PM](https://user-images.githubusercontent.com/25848231/223575029-0056253f-7381-4dea-8188-36b3af3904ba.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3246)

**Comment by iamatifmoin** [comment] 2023-03-08 04:58
@yashikakhurana Please assign this to me.

**Comment by yashikakhurana** [comment] 2023-03-08 17:17
@tessa5 task is already assigned, you need to find other task, let me know if need any help :)

**Comment by tessa5** [comment] 2023-03-09 10:19
@yashikakhurana Well noted. Thank you. I will be sure to reach out if I need help. Thank you. :)

**Comment by Yass32** [comment] 2023-03-09 17:00
Hey @iamatifmoin  can we collaborate on this?

**Comment by yashikakhurana** [comment] 2023-03-09 17:47
@iamatifmoin if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by emmaz12** [comment] 2023-03-09 23:15
@yashikakhurana I am interested in taking on this issue if it becomes available! Thanks again :)

**Comment by iamatifmoin** [comment] 2023-03-10 01:56
> @iamatifmoin if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

I am working on it. 
I am going to make a PR today.

**Comment by Avi-88** [comment] 2023-03-11 22:54
Hello @yashikakhurana ma'am , we can easily achieve this by adding a few classes to the wrapping container. I hope @iamatifmoin succeeds in making a PR for it  , but if you do decide to pass over this issue please do consider assigning it to me, thanks

**Comment by yashikakhurana** [comment] 2023-03-13 18:05
@iamatifmoin still working on this, if not I will assign it to @Avi-88 , please let me know thanks

**Comment by ClaretHellen** [comment] 2023-03-14 11:25
Hello @yashikakhurana 
I am an outreachy applicant and I am looking forward to being assigned a project.
Thank you.

**Comment by iamatifmoin** [comment] 2023-03-14 13:20
> @iamatifmoin still working on this, if not I will assign it to @Avi-88 , please let me know thanks

@yashikakhurana 
apologies for the delay.
I had fixed the issue and was going to make a PR but, since the latest commits, the project is not working on my system.
while I fix this, you can assign someone else. 
thanks.

**Comment by yashikakhurana** [comment] 2023-03-14 16:52
@iamatifmoin what's the issue you are facing? if you can share something if its something I can help with

**Comment by yashikakhurana** [comment] 2023-03-14 16:53
@ClaretHellen let me just check with @iamatifmoin what's the error is if its already done, otherwise I will assign it to you, thanks

**Comment by iamatifmoin** [comment] 2023-03-15 08:03
> @iamatifmoin what's the issue you are facing? if you can share something if its something I can help with

It was working fine earlier but now everything freezes on `make check` or `make refresh`.
I think I'll need more system resources for it.

@yashikakhurana you can assign someone else, I'll help them solve the issue.

**Comment by ClaretHellen** [comment] 2023-03-16 06:36
Hello, @yashikakhurana kindly assign someone else.

**Comment by Avi-88** [comment] 2023-03-16 06:44
> Hello, @yashikakhurana kindly assign someone else.

Hi @ClaretHellen , is there any issue you need help with ? I'll try my best to help so you can give this one more try before deciding to let it go

**Comment by emmaz12** [comment] 2023-03-17 00:34
@yashikakhurana I'm interested in this task!

**Comment by cherish2003** [comment] 2023-03-17 05:40
@yashikakhurana can you assign me this issue

**Comment by cherish2003** [comment] 2023-03-17 19:56
@yashikakhurana kindly review the PR #8537 to close this issue

**Comment by Avi-88** [comment] 2023-03-19 18:20
Hello @cherish2003, I'm glad you could make a contribution but could you please wait until the issue is assigned to you before making a PR. It creates confusion among those who asked for it to be assigned and waited for response from @yashikakhurana ma'am. I'm sure there will be more issues added for the contributors to work on, so I hope you understand, thanks

**Comment by cherish2003** [comment] 2023-03-19 18:48
> Hello @cherish2003, I'm glad you could make a contribution but could you please wait until the issue is assigned to you before making a PR. It creates confusion among those who asked for it to be assigned and waited for response from @yashikakhurana ma'am. I'm sure there will be more issues added for the contributors to work on, so I hope you understand, thanks

Sure sorry for it i thought it is taking time for the issue to be assigned so i made a PR

**Comment by Avi-88** [comment] 2023-03-20 00:43
Also @cherish2003 , I think the PR's that you made have iterative changes from the previous issues that you worked on. I'm guessing that you checked out a new branch not from main but the other branches you worked on which caused them to iterate in each new PR

**Comment by cherish2003** [comment] 2023-03-20 05:42
@yashikakhurana i have PR related to this issue #8537  kindly check it out

**Comment by cherish2003** [comment] 2023-03-20 06:06
> Also @cherish2003 , I think the PR's that you made have iterative changes from the previous issues that you worked on. I'm guessing that you checked out a new branch not from main but the other branches you worked on which caused them to iterate in each new PR. It'll be better if the PR's only had changes related to that specific issue, you might want to recheck that.

@Avi-88 Those are not changes they are  commits for the changes i have done and also it is best pratice for creating different branches for different issues but not merging directly into main branch which will be later done by codebase maintainers thankyou for your suggestion 😀

**Comment by Avi-88** [comment] 2023-03-20 06:21
> > Also @cherish2003 , I think the PR's that you made have iterative changes from the previous issues that you worked on. I'm guessing that you checked out a new branch not from main but the other branches you worked on which caused them to iterate in each new PR. It'll be better if the PR's only had changes related to that specific issue, you might want to recheck that.
> 
> @Avi-88 Those are not changes they are  commits for the changes i have done and also it is best pratice for creating different branches for different issues but not merging directly into main branch which will be later done by codebase maintainers thankyou for your suggestion 😀
> 

I think you misunderstood, I was saying that the commits that were made for other issues are being carried over to a PR for  a completely different issue. I know that we need to create new branch for each change but the new branch should be created by using main branch as base. For eg, your PR for

**Comment by cherish2003** [comment] 2023-03-20 09:58
Okay got it @Avi-88

**Closed** 2023-03-21 18:19 UTC
Labels: Outreachy
