### ISSUE TITLE
Duplicate experiment feature

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3999] opened 2020-11-16 21:18 UTC
Not something we need immediately, but from our early testing I think being able to duplicate an experiment would be really useful (especially when you made a mistake / only want to change 1 thing)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-594)
┆Issue Number: EXP-594

**Comment by LZoog** [comment] 2021-01-29 19:25
Closing this as a dupe of #4048

**Closed by LZoog** 2021-01-29 19:25 UTC
