### ISSUE TITLE
Experiment not showing errors on missing/invalid fields on /branches page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5191] opened 2021-05-07 20:32 UTC
https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-20210506-ddd-application-error/edit/branches?show-errors

If I click the "Branches" link under "Review & Launch" section, it takes me to the experiment's /edit/branches/ page, but I see now visible errors or warnings or indications of what is missing.

![pdehaan-20210506-ddd-application-error_–_Branches___Experimenter](https://user-images.githubusercontent.com/557895/117505061-50967880-af38-11eb-9acf-9850b0612d2a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1287)
┆Issue Number: EXP-1287

**Comment by LZoog** [comment] 2021-05-12 18:29
Ooh, this is a dupe of #5171 which has related issues and when those linked issues addressed (they're in the required for launch epic, our main priority right now) this will be fixed, so I'll go ahead and close this.

**Closed by LZoog** 2021-05-12 18:29 UTC
