### ISSUE TITLE
I can request approval for a rapid experiment I'm not the owner of

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3149] opened 2020-07-29 01:08 UTC
Not sure if this is a bug or just "how it works"(tm), but I was looking at https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/fastest-of-the-fast and noticed that I can apparently/probably request approval for an experiment I don't own.

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/88744667-de694b80-d0fc-11ea-954b-f9fd1e3d57df.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-208)
┆Issue Number: EXP-208

**Comment by data-sync-user** [comment] 2020-09-30 19:02
➤ Wil Clouser commented:

This is by design.  I'm going to close this but CC [~amedinac@mozilla.com]  in case it's something she wants to change in the future.

**Closed by data-sync-user** 2020-09-30 19:02 UTC
