### ISSUE TITLE
Support defining traffic percentage in UI

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#3253] opened 2020-08-18 13:36 UTC
In order to move past A/A experiments that are always fixed to 1% of the population, we should add a input to the UI to specify what percentage of the population the experiment should be released to.

Let's make sure this is highly visible in the overview / add a warning if it's about 1%.

Obviously this will require assistance from data science to figure out what the percentage will be until we implemented some automation around suggestion appropriate values, in the meantime let's add a help text disclaimer saying `"please consult a data scientist to determine an appropriate value by filing a data science Jira ticket."`

Link "data science Jira ticket" to https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=109990007

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-68)
┆Issue Number: EXP-68

**Comment by jaredlockhart** [comment] 2020-08-18 16:09
I think we'll need to also define a minimum percentage to ensure automated analysis gets the number of clients it needs

**Comment by k88hudson** [comment] 2020-08-18 16:09
Just as a note, because some audiences (e.g. first run) limit the population, a higher percentage may be necessary so we will need to revisit this eventually

**Comment by data-sync-user** [comment] 2020-11-03 21:35
➤ Jared Kerim commented:

Closing as duplicate of https://jira.mozilla.com/browse/EXP-488

**Closed by data-sync-user** 2020-11-03 21:35 UTC
Labels: API, Nimbus-Experimenter, Web UI
