### ISSUE TITLE
E[t] is undefined on results page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9764] opened 2023-11-16 22:40 UTC
I'm seeing a crash on multiple results pages:

```
General application error

Something went wrong. Please try again later.
E[t] is undefined
```

on the following recently ended experiments:

https://experimenter.services.mozilla.com/nimbus/ios-onboarding-search-widget/results
https://experimenter.services.mozilla.com/nimbus/release-validation-c/results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4036)

**Comment by mikewilli** [comment] 2023-11-17 16:40
Closing as duplicate of #9700

**Closed by mikewilli** 2023-11-17 16:40 UTC
