### ISSUE TITLE
Nimbus experiment slug isn't recalculated if experiment is renamed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4052] opened 2020-11-19 18:06 UTC
Possibly by design, but maybe worth clarification

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/new

1. Create a new dummy experiment.
1. Set the name to something random.
1. Click the "Create experiment" button.
	- If successful, the experiment slug will be generated by a slugified version of the experiment name.
1. On the [/edit/overview page](https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/the-quick-brown-foxs/edit/overview), rename the "Public name" field to something different.

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99705322-6e395980-2a4e-11eb-86a3-9536fe875bc4.png)
**Figure 1:** Before.

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99705439-932dcc80-2a4e-11eb-9a26-0f6191edd767.png)
**Figure 2:** After. Note that the name changed, but the slug stayed the same. This is good for consistency and not breaking URLs or having to think about redirects, but could be awkward if your original slug had a typo or something you wanted to change but the slug is locked once created and you don't realize that changing the public name won't fix the slug.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-633)
┆Issue Number: EXP-633

**Comment by lmorchard** [comment] 2020-11-19 19:16
IIRC, this is by design, we don't want to allow slug renaming after initial creation

**Comment by data-sync-user** [comment] 2020-11-19 19:59
➤ Les Orchard commented:

If we want to do this, I think it might be a little hairy: If the slug is recalculated, the current page will need to be redirected to match the new slug. I think we punted doing this at least for that reason

**Comment by pdehaan** [comment] 2020-11-19 21:20
I'm fine to close this. Doesn't look like renaming the experiment on the old rapid experiments regenerated the slug either.

https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/peter-slug-test-2/

**Comment by data-sync-user** [comment] 2020-11-19 22:57
➤ Lauren Zugai commented:

In one of the original Figma designs, we were going to allow users to change the slug if they wanted but decided against it to decrease complexity while building out the create/edit flow. We were going to possibly revisit this later, but that's also different than automatically regenerating the slug when the user updates the name. [~amedinac@mozilla.com] [~khudson@mozilla.com] would probably be good to have your input here on if we should close this, implement auto regenerating it based on the new name, or implement allowing users to change the slug themselves.

**Comment by data-sync-user** [comment] 2020-11-20 18:24
➤ Kate Hudson commented:

The use case for being able to change it is if users have implemented something with a specific slug in mind already, so definitely allowing them to change the slug themselves is the right thing to pick here.

There's not really a real use case for regenerating a new one I don't think

**Comment by pdehaan** [comment] 2020-11-20 21:22
Figma note to the rescue. Apparently it was called out that the user would be unable to change/edit the slug.

<img width="335" alt="Nimbus_Console_UI_–_Figma" src="https://user-images.githubusercontent.com/557895/99851044-4a9c0f00-2b33-11eb-8121-3251a29c4481.png">

I'm fine with this not being possible (or only being possible w/ the help of somebody hand editing in the database or admin UI and something an end user can't directly do).

**Closed** 2020-12-03 22:46 UTC
