### ISSUE TITLE
"Completed" view should sort by most recently ended

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4782] opened 2021-03-09 19:13 UTC
It's hard to find recent experiments in https://experimenter.services.mozilla.com/nimbus/ on the "Completed" tab. It would be nice if recently ended experiments were at the top of the list.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1046)
┆Issue Number: EXP-1046

**Comment by LZoog** [comment] 2021-05-25 16:49
I'm going to close this as a dupe of #5281 since that one covers all tabs and has more discussion.

**Closed by LZoog** 2021-05-25 16:49 UTC
