### ISSUE TITLE
Add total enrolled clients to detail page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7845] opened 2022-10-13 20:37 UTC
We're not showing the total enrolled clients on the detail page, we should add that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2849)

**Comment by yashikakhurana** [comment] 2023-03-06 23:56
To add more context detail page meaning summary page, in audience section

**Comment by iamrahul823** [comment] 2023-03-07 04:47
Hello @yashikakhurana. I am an Outreachy applicant and I would love to participate in this project by working on this issue.

**Comment by yashikakhurana** [comment] 2023-03-07 17:12
@iamrahul823 sure assigning it to you, thank you, and let me know if you have any questions. I saw your comments on other issues too, once you finish this, I can assign the others too, but will recommend finishing this first. Once you submit a PR, tag me again any other issue you want to work on :)

**Comment by Avi-88** [comment] 2023-03-11 23:04
Hello @yashikakhurana ma'am, I checked out the page you referred to and just wanted to clarify that we just need to replace the "Expected enrolled clients" with "Total enrolled clients" right ? Also if possible I would like to work on this issue , thanks

**Comment by Philipotieno** [comment] 2023-03-12 20:47
Hi @yashikakhurana Outreachy applicant here, I would love to work on this issues I see it's no longer assigned to anyone.

**Comment by Sprof22** [comment] 2023-03-12 23:23
@yashikakhurana I am an Outreachy applicant, can I be assigned to this issue. I am free and available. I will solve issue within the hour it is assigned to me.

**Comment by Avi-88** [comment] 2023-03-13 22:27
I'm sorry if i'm asking the obvious @yashikakhurana ma'am , but there is already a `Expected enrolled clients` field on the summary page in the audience section which uses the `totalEnrolledClients` value from the said experiments data.

![highlight](https://user-images.githubusercontent.com/79744258/224846323-476ac53e-180a-4459-bd95-2e63b9860908.png)


 Is this `Expected number of clients` field you mentioned different from the one already present and if yes which value from the experiment data should I use to represent it . Please let me know if I got anything wrong and I'll work on it, thanks

**Comment by yashikakhurana** [comment] 2023-03-13 22:56
@Avi-88 thank you for getting back, yes it is present, but if the value is 0, then this field is not rendered on summary page, we want to show that even if its 0 expected enrolled clients and that's the cause too with this weird formatting 
![image](https://user-images.githubusercontent.com/25848231/224850563-3f97a82f-5b6a-4a6a-9606-d1287ac25088.png)
let me know if you have further questions :)

**Comment by Avi-88** [comment] 2023-03-13 23:05
> @Avi-88 thank you for getting back, yes it is present, but if the value is 0, then this field is not rendered on summary page, we want to show that even if its 0 expected enrolled clients and that's the cause too with this weird formatting ![image](https://user-images.githubusercontent.com/25848231/224850563-3f97a82f-5b6a-4a6a-9606-d1287ac25088.png) let me know if you have further questions :)

Understood, so even if the `totalEnrolledClients` value is zero we should still render it so that the formatting doesn't get messed up. I'll make the required changes, thankyou for clarifying that

**Closed** 2023-03-16 17:54 UTC
Labels: Outreachy
