### ISSUE TITLE
Use a package manager to handle 3rd party dependencies?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#967] opened 2019-02-20 19:48 UTC
> Ideally, I think the static stuff like jquery and font-awesome should NOT be checked into git but instead a build artifact. I.e. list the packages we need in a `package.json`, run `yarn` to make them available in `./node_modules/**` and Django then copies the stuff it needs and runs `./manage.py collectstatic` and those files that get copied (and minified etc.) are added to the docker image which CircleCI then ships to DockerHub (or whatever the equivalent tech is going to be). 
> 
> There are, though, a bunch of files inside https://github.com/mozilla/experimenter/tree/master/app/experimenter/static/lib/fontawesome that are never ever used. For one, we either use `fontawesome.js` or we use `fontawesome.min.js` but not the other.

_Originally posted by @peterbe in https://github.com/mozilla/experimenter/issues/965#issuecomment-465691488_

---

It looks like we currently have three 3rd party dependencies in https://github.com/mozilla/experimenter/tree/master/app/experimenter/static/lib:

- Bootstrap 4.1.3 (latest is v4.3.1, per https://getbootstrap.com/)
- Font Awesome Free 5.3.1 (ref: #966 to bump to v5.7.2)
- jquery 3.2.1  (ref: #959 to bump to v3.3.1)

**Comment by pdehaan** [comment] 2019-02-20 19:56
Bumping **jQuery** seems [fairly sane](https://github.com/mozilla/experimenter/pull/959/files) currently where we really only need to replace a single file and update the `<script src="...">`.

Bumping **Font Awesome** is a bit more complex at about 1568 files changed, and a massive [+38,827 lines and -20,703 lines](https://github.com/mozilla/experimenter/pull/966/files) diff.

**Comment by jaredkerim** [comment] 2019-08-22 19:30
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/1554

**Comment by jaredlockhart** [comment] 2020-06-01 21:00
Looks like we might finally get this....

**Closed** 2020-06-02 18:53 UTC
Labels: Task, Tech Debt, Web UI
