### ISSUE TITLE
Authors should be able to cancel a review request

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5733] opened 2021-06-21 08:53 UTC
We ran into a scenario where:

* The author requested review
* They realized something was wrong and needed to edit again

We should let authors go back to draft from a in review state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1305)

**Comment by jaredlockhart** [comment] 2021-08-20 20:37
Closing as dupe of https://github.com/mozilla/experimenter/issues/5637

**Closed by jaredlockhart** 2021-08-20 20:37 UTC
