### ISSUE TITLE
Results links don't navigate to results page

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4704] opened 2021-02-25 15:00 UTC
If you're on the design page of a completed experiment, none of the results links take you to the results page unless you click the 'Results' link at the top first.  They should probably all take you to the results page.
![2021-02-25 09-58-16 2021-02-25 09_59_23](https://user-images.githubusercontent.com/119884/109171916-3a0dbd00-7750-11eb-9b99-b1e4d76521ef.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1013)
┆Issue Number: EXP-1013

**Comment by jodyheavener** [comment] 2021-02-25 16:01
Might be able to close this as dupe as there is already a conversation about this in #4585

**Comment by LZoog** [comment] 2021-02-25 17:52
Ah yeah, this is definitely a dupe of #4585, I'll add it to the next sprint!

**Closed by LZoog** 2021-02-25 17:52 UTC
