### ISSUE TITLE
Update Experimenter pref flip intake to support multiple preferences

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1176] opened 2019-04-11 19:19 UTC
After the Normandy client lands in Firefox 69 or 70 (Release in Sept 3 or October 22) - Experimenter will need to be updated the intake multiple preferences per branch (if desired).

UX pending implementation details (what is the client going to need - what format).

**Comment by jaredkerim** [comment] 2019-08-22 19:28
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/1421

**Closed by jaredkerim** 2019-08-22 19:28 UTC
Labels: Enhancement
