### ISSUE TITLE
Release v2.31.x

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#1427] opened 2019-07-02 22:36 UTC
- [x] Create 2.32.0 Milestone (due date two weeks from now)
- [x] Move all open tickets in 2.31.0 to 2.32.0
- [x] Close 2.31.0 Milestone
- [x] Approve and merge all open dependabot PRs
- [x] Pull master
- [x] Ensure `make check` passes
- [x] `git tag v2.31.0;git push --tags`
- [x] `@here deploying v2.31.0 to stage https://github.com/mozilla/experimenter/milestone/55?closed=1` in #experimenter 
- [x] Verify that stage loads with v2.31.x
- [x] Verify that recipe API is whitelisted on stage
- [x] Received *YELLOW* testing report from QA
- [x] `@robotblake please push v2.31.x to production` in #experimenter 
- [x] Verify that prod loads with v2.31.x
- [x] Verify that recipe API is whitelisted on prod
- [x] Create release issue for `Release v2.32.x`

**Comment by uhlissuh** [comment] 2019-07-09 20:52
@jaredkerim should we also add, 
"close any point release milestones that have launched to stage"?

**Comment by uhlissuh** [comment] 2019-07-09 21:05
Also should we acually be tagging all the dependabot issues we merge with the milestone? If so, we need to wait to close the milestone until after doing that.

**Comment by jaredkerim** [comment] 2019-07-09 22:01
@uhlissuh 

- You can close a point release milestone as soon as its deployed, so basically immediately.

- Dependabot doesn't create issues, only PRs, and we don't tag PRs with milestones for no particular reason, so no you don't need to tag them with the milestone.  The commit will get highlighted with the tag its in if you really need to check when something was deployed.

**Comment by zyjenny** [comment] 2019-07-10 19:42
Hi @uhlissuh! I have a favour to ask :pray

Would it be possible to include the fix for issue https://github.com/mozilla/experimenter/issues/1446 in stage please? 

[this was the PR: https://github.com/mozilla/experimenter/pull/1449 , which I merged in this morning]

**Comment by uhlissuh** [comment] 2019-07-11 22:31
we are doing point release 2.31.2 with a fix for issue #1453!

**Comment by jaredkerim** [comment] 2019-07-15 17:19
Ops whitelisting for recipe apis is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1565686

**Comment by uhlissuh** [comment] 2019-07-16 20:45
v2.31.3 was deployed! check miletstone for the 4 issues it addressed.

**Comment by Softvision-RemusDranca** [comment] 2019-07-22 15:04
Hi team,

We finalized testing the new stage deployment v2.31.0 and it’s dot releases (v2.30.1, v2.30.2 and v2.30.3) on Experimenter website. Here are the results:

New issues: 
#1455 - The Firefox “ Max Version” can wrongly be saved if it is lower than the “Firefox Min Version” - major
#1474 - The URLs added in the "Survey URLs" and "Survey Launch Instructions" input fields are not hyperlinked on the main page of the experiment - normal
#1460 - Nothing happens when the "Help" buttons from the "Firefox Channel" and "Firefox Versions" section are clicked - normal
#1478 - The "Locales" and "Countries" sections aren't updated in the "Experiment Bugzilla Ticket" if they are saved with the "All" default value - normal

QA’s recommendation:  YELLOW - SHIP IT CONDITIONALLY

Reasoning: 
- Although the new issue #1455 is a major one, we don’t consider it as a blocker for this release as it is already fixed on the dev server. 
- The testing report does not cover the functionalities of the emails that are sent for experiments that go live/end or the emails for when the enrollment is paused. Therefore we cannot say for sure if the functionality works as intended since end-to-end testing is not yet possible.

Testing Summary:
- Mac 10.14 - [Test Run](https://testrail.stage.mozaws.net/index.php?/runs/view/18933&group_by=cases:section_id&group_order=asc&group_id=49320) (Acceptance suite).
- Mac 10.14 - [Test Run](https://testrail.stage.mozaws.net/index.php?/runs/view/19133&group_by=cases:section_id&group_order=asc&group_id=46346) (Full Functional suite on the “Population” section).
- Windows 10 x64 - Performed exploratory testing.

Tested Platforms:
- Windows 10 x64
- macOS 10.14

Tested Firefox versions:
- Firefox Release 68.0
- Firefox Release 68.0.1

Regards,
Remus

**Comment by uhlissuh** [comment] 2019-07-22 21:50
This release has been completed.

**Closed by uhlissuh** 2019-07-22 21:50 UTC
Labels: Task
