### ISSUE TITLE
Inconsistent experiment durations on experiment summary page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#5372] opened 2021-06-04 23:05 UTC
Per https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/presents-are-awesome

![Presents_are_awesome___Experimenter](https://user-images.githubusercontent.com/557895/120870724-79695800-c54e-11eb-9da9-10ea51688209.png)

The header area says June 4-July 1 is 27 days, whereas the timeline view says June 4 to July 1 is a duration of 28 days.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1391)
┆Issue Number: EXP-1391

**Comment by jaredlockhart** [comment] 2021-06-07 15:53
Duplicate of https://github.com/mozilla/experimenter/issues/4945

**Comment by data-sync-user** [comment] 2021-06-07 15:55
➤ Lauren Zugai commented:

Going to close this as a dupe of EXP-1381 / #5357 as this should be addressed there.

**Closed by data-sync-user** 2021-06-07 15:55 UTC
