### ISSUE TITLE
Remove type from Design serializers

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1919] opened 2019-11-14 21:46 UTC
We left the 'type' field in the design serializers from an earlier design of the API but we should get rid of those.

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/serializers.py#L606

**Comment by jaredkerim** [comment] 2019-11-14 21:48
https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/serializers.py#L527-L529

**Comment by uhlissuh** [comment] 2019-12-10 00:12
this is a duplicate of another issue that's already fixed.

**Closed** 2019-12-10 00:12 UTC
Labels: P5 - Low Priority, Task
