### ISSUE TITLE
Markup in signoff labels appears as markup in history

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#1431] opened 2019-07-04 19:31 UTC
The link in the QA Jira signoff label displays as markup in the History:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/173889/60685355-87406b00-9e57-11e9-9832-98887089583d.png">

seen at https://experimenter.services.mozilla.com/experiments/webrender-amd-performance-68/

**Comment by jaredkerim** [comment] 2019-07-04 19:35
@tdsmith Thanks for catching and filing, but you're too slow, it's already fixed! :D 

Closing as duplicate of https://github.com/mozilla/experimenter/issues/1288

**Closed by jaredkerim** 2019-07-04 19:35 UTC

**Comment by tdsmith** [comment] 2019-07-04 19:40
🎉 thanks!
