### ISSUE TITLE
Remote settings publishing / external API should validate against `Experiment` schema in mozilla/nimbus-shared

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#2883] opened 2020-06-23 15:58 UTC
As of v0.3, we've published an `Experiment` schema compatible with the current version of Firefox – the v3 API / remote settings publishing should validate against this.

**Comment by jaredlockhart** [comment] 2020-06-24 18:16
Duplicate of https://github.com/mozilla/experimenter/issues/2688

**Closed by jaredlockhart** 2020-06-24 18:16 UTC
