### ISSUE TITLE
Add tooltips to Metrics probe sets

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4169] opened 2020-12-08 17:41 UTC
From the [Figma spec](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216065%3A10550):

> This tooltop explains what probe sets are. copy TBD.

<img width="1146" alt="Nimbus_Console_UI_–_Figma" src="https://user-images.githubusercontent.com/557895/101519576-2c5a4f80-3938-11eb-8229-f1ccb678be99.png">

### Current status

![pdehaan_2020-12-08_001_–_Metrics___Experimenter](https://user-images.githubusercontent.com/557895/101520265-15682d00-3939-11eb-9e44-51a4611734e5.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-695)
┆Issue Number: EXP-695

**Comment by LZoog** [comment] 2020-12-08 21:36
Closing as a dupe of #3746

**Closed by LZoog** 2020-12-08 21:36 UTC
