### ISSUE TITLE
The Preview Recipe JSON link does not focus the Recipe JSON field anymore

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8230] opened 2023-02-01 09:42 UTC
**[Prerequisites]:**

* Have an experiment page open.

**[Steps to reproduce]:**

1. Click the “Preview Recipe JSON” link from the sidebar.
1. Observe the behavior displayed.

**[Expected result]:**

* The “Recipe JSON #” field is focused.

**[Actual result]:**

* The page seems to reload and the field is not focused.

**[Notes]:**

* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3115)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33524">preview recipe.gif</a>

**Comment by eliserichards** [comment] 2023-02-23 18:08
Closing as dupe of #6801

**Closed by eliserichards** 2023-02-23 18:08 UTC
