### ISSUE TITLE
See which experiments have significant results in the directory view

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6275] opened 2021-08-23 18:13 UTC
I want to be able to see which experiments have significant results in the directory view, so I know which experiments have important insights.

My use case here is that I want to demo the visualizations tool to some new stakeholders with some experiments that had particularly interesting results, and I have to really dig through each one to find examples.

┆Issue is synchronized with this [Jira EXP Request](https://mozilla-hub.atlassian.net/browse/EXP-1671)

**Comment by jaredlockhart** [comment] 2022-01-28 21:01
@shell1 please add this to a reporting epic 🙏

**Comment by jaredlockhart** [comment] 2023-02-09 15:05
Closing as dupe of https://github.com/mozilla/experimenter/issues/8252

**Closed by jaredlockhart** 2023-02-09 15:05 UTC
Labels: Request
