### ISSUE TITLE
Open RS should link to the exact page where the approval happens

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#5254] opened 2021-05-13 21:00 UTC
Instead of linking to the general remote settings link, we should link to the exact approval page to prevent accidentally approving the wrong request.

e.g. for desktop experiments, 
https://settings-writer.prod.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/records

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1319)
┆Issue Number: EXP-1319

**Comment by lmorchard** [comment] 2021-05-13 23:47
I think this is a dupe of https://github.com/mozilla/experimenter/issues/5041

**Comment by data-sync-user** [comment] 2021-05-18 22:05
➤ Jared Kerim commented:

[~lorchard@mozilla.com] yep it is, good catch, closing.

**Closed by data-sync-user** 2021-05-18 22:05 UTC
Labels: quick-win
