### ISSUE TITLE
Getting a "feature not available on this version" error with JSON branch review because targeting same min/max version

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#11963] opened 2024-12-17 16:34 UTC
https://experimenter.services.mozilla.com/nimbus/disabling-chips-for-v131-only/summary is the one hitting branch issues.

We are targeting min 131 and max 131.  we only want it to go to that one version.  We are getting an incorrect JSON branch error that says "feature not available on this version"

We know the feature is in 131 - and this rollout (with no min version) is running https://experimenter.services.mozilla.com/nimbus/disabling-chips-for-v131/audience

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-5065)

**Comment by data-sync-user** [comment] 2024-12-17 18:54
➤ Beth Rennie commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/EXP-4692 ( https://mozilla-hub.atlassian.net/browse/EXP-4692|smart-link ) (https://github.com/mozilla/experimenter/issues/11002 ( https://github.com/mozilla/experimenter/issues/11002|smart-link ) )

**Closed** 2024-12-17 18:53 UTC
