### ISSUE TITLE
Update docs to include setting `FEATURE_ANALYSIS`

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#4382] opened 2021-01-08 17:44 UTC
This can be set to true in the `.env` file and the docs need to be updated to reflect this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-813)
┆Issue Number: EXP-813

**Comment by LZoog** [comment] 2021-01-11 17:56
Oh oops, I didn't see this before creating my own ticket, closing as a dupe of #4386

**Closed by LZoog** 2021-01-11 17:56 UTC
