### ISSUE TITLE
Intermittent Design Page Integration Test 

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#2178] opened 2020-01-16 19:11 UTC
We've seen this before.... seems like it came back....
`selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #id_pref_key`

**Comment by jaredlockhart** [comment] 2020-01-20 19:48
While we're at it I just hit another one if two variants randomly get the same name:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/static/js/tests/AddonForm.test.js#L77

```
Error: Found multiple elements with the value: corporis.

(If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).

<body>
  <div>
    <div>
      <div
        class="container"
      >
        <form
          id="design-form"
        >
          <div>
            <div
              class="row"
            >
              <div
                class="col-md-10 offset-md-2"
              >
                <div
                  class="mb-4 form-group"
                >
                  <div
                    class="form-row"
                  >
                    <label
                      class="form-label"
                    >
                      <h5>
                        How many add-ons does this experiment ship?
                      </h5>
                    </label>
                  </div>
                  <div
                    class="mb-2 form-check"
                  >
                    <input
                      class="form-check-input"
                      id="is_branched_addon-false"
                      name="is_branched_addon"
                      type="radio"
                      value="false"
                    />
                    <label
                      class="form-check-label"
                      for="is_branched_addon-false"
                      title=""
                    >
                      A single add-on for all branches
                    </label>
                  </div>
                  <div
                    class="mb-2 form-check"
                  >
                    <input
                      class="form-check-input"
                      id="is_branched_addon-true"
                      name="is_branched_addon"
                      type="radio"
                      value="true"
                    />
                    <label
                      class="form-check-label"
                      for="is_branched_addon-true"
                      title=""
                    >
                      Multiple add-ons
                    </label>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-testid="addonUrl"
            >
              <div
                class="mb-3 row"
              >
                <div
                  class="text-right col-md-2"
                >
                  <label
                    class="form-label"
                  >
                    <strong>
                      Signed Add-On URL
                    </strong>
                    <div
                      class="required-label required"
                    >
                      <div
                        class="text-danger"
                      >
                        Required
                      </div>
                    </div>
                  </label>
                  <div>
                    <a
                      href="#"
                      name="addon_release_url"
                    >
                      Help
                    </a>
                  </div>
                </div>
                <div
                  class="col-md-10"
                >
                  <input
                    class="form-control"
                    name="addon_release_url"
                    type="text"
                    value="http://agustin.net"
                  />
                  <div
                    class="text-muted collapse mt-2"
                  >
                    <div>
                      <p>
                        Enter the URL where the release build of your add-on can be found. This is often attached to a bugzilla ticket. This MUST BE the release signed add-on (not the test add-on) that you want deployed. 
                        <a
                          href="https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Add-ons"
                          rel="noreferrer noopener"
                          target="_blank"
                        >
                          See here for more info.
                        </a>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <hr
              class="heavy-line my-5"
            />
            <div
              data-testid="branch0"
              id="control-branch-group"
            >
              <div
                class="mb-3 row"
              >
                <div
                  class="col-md-4 offset-md-2"
                >
                  <h4>
                    Control Branch
                  </h4>
                </div>
                <div
                  class="text-right col-md-6"
                />
              </div>
              <div
                class="mb-3 row"
              >
                <div
                  class="text-right col-md-2"
                >
                  <label
                    class="...
```

**Comment by tiftran** [comment] 2020-01-31 12:33
Circle CI integration test failure link: https://circleci.com/gh/mozilla/experimenter/7143

**Comment by jaredlockhart** [comment] 2020-02-25 15:48
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/2178

**Closed by jaredlockhart** 2020-02-25 15:48 UTC
Labels: Defect, Tests
