### ISSUE TITLE
The invalid image error text overlaps the screenshot added to one of the branches

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8179] opened 2023-01-23 14:44 UTC
**[Prerequisites]:** 

* Have a newly created Nimbus experiment with the “Branches” section not completed yet.
* Have the Nimbus Experiment Page opened.
* Have this [image](https://drive.google.com/file/d/1lzJlW6NqmCFUu-TAelRC6G0t4pmiU2f4/view?usp=share_link) downloaded on your machine.

**[Steps to reproduce]:**

1. Select the “Branches” section from the Navigation Menu.
1. Upload the image from prerequisites.
1. Observe the error displayed.

**[Expected result]:**

* The error displayed does **NOT** overlap the uploaded screenshot.

**[Actual result]:**

* The error text overlaps the screenshot.

**[Notes]:** 

* This issue is reproducible on Firefox Nightly 111.0a1 on macOS 12.4.
* This issue is reproducible on any resolution of the browser. 
* Attaching a screenshot of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3079)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33247">The invalid image error text overlaps the screenshot added to one of the branches.png</a>

**Comment by yashikakhurana** [comment] 2023-03-09 17:53
@wangare-i if you are not working, I have to remove your assignment, let me know otherwise tomorrow I will remove your assignment as other applicants are waiting to get assigned, kindly submit a PR.

**Comment by Philipotieno** [comment] 2023-03-14 20:39
Hi @yashikakhurana I am outreachy applicant is is this issue still open?
If yes, you can assign me

**Comment by Philipotieno** [comment] 2023-03-15 08:06
Hi @yashikakhurana 
I am trying to reproduce the issue
I have requested access to the image

**Comment by yashikakhurana** [comment] 2023-03-15 20:10
@Philipotieno here is the image- 
![Uploading image.png…]()

**Comment by Mehak-4545** [comment] 2023-03-20 23:12
Hello @yashikakhurana , I feel that I could try my hand at resolving this issue. If this issue is open and unresolved, can it be assigned to me as well?

**Comment by Philipotieno** [comment] 2023-03-21 00:32
You can work on the issue, @yashikakhurana  should assign it since I have another issue I am working on, we can later sync and help testing and reviewing the changes

**Comment by Mehak-4545** [comment] 2023-03-22 17:26
@Philipotieno Can you tell me how exactly you created a Nimbus experiment to see the issue? Also I'm unable to view the image without permission. I'm assuming you have already worked a bit on this issue and could guide me on this. Thanks!

**Comment by yashikakhurana** [comment] 2023-03-22 17:29
@Mehak-4545 I have already added a screenshot here- https://github.com/mozilla/experimenter/issues/8179#issuecomment-1470772246

**Comment by Philipotieno** [comment] 2023-03-25 20:04
@Mehak-4545 if you upload an invalid image you'll see the error as displayed by on screenshot provided by @yashikakhurana

**Comment by Jemeelah1** [comment] 2023-03-29 23:09
@yashikakhurana can i work on this

**Comment by Jemeelah1** [comment] 2023-03-31 13:30
@yashikakhurana i need access to the image on google drive, i sent a request

**Comment by yashikakhurana** [comment] 2023-03-31 17:10
@Jemeelah1 you don't need access- you can find image here- https://github.com/mozilla/experimenter/issues/8179#issuecomment-1470772246

**Comment by cherish2003** [comment] 2023-04-02 09:37
@yashikakhurana it seems like @Jemeelah1 is not working on this issue can i work on this

**Comment by Jemeelah1** [comment] 2023-04-02 11:52
@cherish2003 I am working on it

**Comment by Jemeelah1** [comment] 2023-04-03 09:25
<img width="1792" alt="Screenshot 2023-04-03 at 10 22 23 AM" src="https://user-images.githubusercontent.com/83028679/229468493-ab54f380-c140-4dcb-8462-4a64a74337cb.png">
I don't have access to the local host, keeps saying access denied when i try to start the project @yashikakhurana 
Kindly assist.

**Comment by yashikakhurana** [comment] 2023-04-03 16:56
@Jemeelah1 can you do `localhost/nimbus/`

**Comment by yashikakhurana** [comment] 2023-04-04 21:33
@Jemeelah1 no it doesn't use any packages, I will suggest following readme again for set up

**Comment by Jemeelah1** [comment] 2023-04-04 21:34
@yashikakhurana I will go through it again, thank you

**Comment by cherish2003** [comment] 2023-04-09 17:45
@Jemeelah1 are working on this issue can you let me know if not i would like to work on it

**Comment by yashikakhurana** [comment] 2023-04-26 16:42
work done in this ticket- https://github.com/mozilla/experimenter/pull/8677

**Closed by yashikakhurana** 2023-04-26 16:42 UTC
Labels: Outreachy

**Comment by Philipotieno** [comment] 2023-04-26 22:11
@cherish2003 great work, I saw your PR,
I had also adjusted the _margin-top_ so as the error not to overlap the image, on full-screen it was okay but when I tried to lead it on a smaller screen the error still overlapped the image.

**Comment by data-sync-user** [comment] 2023-05-10 17:54
➤ Shell Escalante commented:

outreach accepted and will join May 29th start day!!!!  Got our first choice.  Avi!!!

**Comment by data-sync-user** [comment] 2023-06-14 10:12
➤ Ciprian Muresan commented:

I have verified that the issue is no longer reproducible on the current version of the Stage server ({"commit": "bf6c26ed772edeb967fc419e103ef265f68b3884", "source": "https://github.com/mozilla/experimenter.git%22, ( https://github.com/mozilla/experimenter.git%22,|smart-link )  "build": "https://circleci.com/gh/mozilla/experimenter/88840"} ( https://circleci.com/gh/mozilla/experimenter/88840%22%7D )). The error message now pushes the image down so that no overlap occurs.
