### ISSUE TITLE
The "Server Error (500)" error is displayed after saving the experiment if a string value is entered without quotes in the "Pref Value" section

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1032] opened 2019-03-08 15:25 UTC
**[Affected versions]:**
- Firefox Release 65.0.2 and above
- Chrome 72.0.3626.121

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Branches" section.
4. Enter a sting with No quotes in the "Pref Value" input field.
5. Click the "Save Draft" button and observe the behavior.

**[Expected result]:**
- The "! This is not a valid JSON" error message is displayed.

**[Actual result]:**
- The "Server Error (500)" error is displayed. 

**[Notes]:**
- This issue is also reproducible when the experiment is saved with no value in the "Pref Value" input field.
- This issue is not reproducible when entering strings with quotes or inserting the true or false values in the "Pref Value" input field.
- This issue is not reproducible when entering numbers in the "Pref Value" input field.
- Attached is a screen recording of the issue:
![branchvalue](https://user-images.githubusercontent.com/40061643/54037486-f6b68e80-41c6-11e9-9537-d8c05b41681e.gif)

**Comment by leplatrem** [comment] 2019-03-11 11:50
`KeyError: 'value'`

This was introduced by #905 

https://github.com/leplatrem/experimenter/blob/bd97f14f624ad7ab4afa8dc50a48681eae06e6c1/app/experimenter/experiments/forms.py#L265-L273

**Comment by leplatrem** [comment] 2019-03-11 14:22
I can't reproduce on current master. It seems that d688bedcf123e9d865ffdd4d090ce6ce2fdeee15 fixed it (?)

**Comment by jaredkerim** [comment] 2019-03-12 20:47
@leplatrem Yes it was fixed by https://github.com/mozilla/experimenter/issues/382, so I will cherry pick  https://github.com/mozilla/experimenter/commit/d688bedcf123e9d865ffdd4d090ce6ce2fdeee15 into this release.

**Closed by jaredkerim** 2019-03-12 20:47 UTC
Labels: [QA]:Blocker issue, [QA]:Regression

**Comment by Softvision-RemusDranca** [comment] 2019-03-14 13:50
I have verified this issue and it's no longer reproducible on the "https://experimenter.stage.mozaws.net/" website after the (v2.25.1) deployment.
Tested on Windows 10x64, MacOS 10.14 and Arch Linux 4.16.6 x64.
